### ISSUE TITLE
policykit-0.9_10 has large number of unnecessary dependents.

### ISSUE THREAD

**Issue by mrT55** [trueos/trueos-ports#45]
After doing a fresh install of Trident-x64-20180831.iso (release)
pkg install policykit  (version 0.9_10)

It wants to install 42 dependents!
This appears to be execssively unnecessary.

pkg --version
1.10.51.10.5

trident-core-201808290904
FreeBSD 12.0-CURRENT #0

**Comment by mrT55** [comment]
The same version of policykit installed on pcbsd-10.3 only has 5 dependents:
```
pkg info --dependencies policykit |less
policykit-0.9_10:
        libxml2-2.9.3
        expat-2.2.0
        dbus-glib-0.104
        glib-2.46.2_2
        gettext-runtime-0.19.8.1
```

**Comment by miwi-fbsd** [comment]
This is a known issue and should be reported at https://bugs.freebsd.org.
