### ISSUE TITLE
print/cups-2.2.8_1 missing ippfind utility

### ISSUE THREAD

**Issue by mrT55** [trueos/trueos-ports#50]
the cups error log shows:
    E [16/Sep/2018:11:26:28 -0400] [CGI] Unable to execute ippfind utility: No such file or directory

I did search the system and did not find it.
pkg info --list-files cups
    did not find it.

Installed from:
   http://pkg.project-trident.org/pkg/release/ports/FreeBSD%3A12%3Aamd64/latest/All/cups-2.2.8_1.txz
pkg-plist has it listed!
However, ippfind binary executable is not found.

NOTE: ippfind  was in: cups-2.1.4

https://github.com/trueos/trueos-ports/blob/trueos-master/print/cups/Makefile
 trueos-ports/print/cups/Makefile
 Branch: trueos-master

PORTVERSION= 2.2.8

pkg-plist has it listed!

it is found in:
```
github.com/apple/cups/
searched for 'ippfind'
    test/ippfind.c
    doc/help/man-ippfind.html
    man/ippfind.man
    man/Makefile
    packaging/cups.spec.in
    CHANGES.md
    packaging/cups.list.in
    configure
```

**Comment by miwi-fbsd** [comment]
Hi,

Is that still an issue?

**Comment by miwi-fbsd** [comment]
no feedback
