### ISSUE TITLE
easytag is window only. no navigation

### ISSUE THREAD

**Issue by RodMyers** [trueos/trueos-ports#56]
sudo about
Password:

===================
General information
===================

boot environment now (N) … 12.0-CURRENT-201810081824 NR 2018-10-08
       after restart (R) … 12.0-CURRENT-201810081824 NR 2018-10-08
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
    number of cores ……………… 4
host ……………………………………………………… laptop.hitwe-8.org
memory ………………………………………………… 12288 MB available, 7684 MB free
OS git branch ……………………………………………………………………………………… Mon
OS git revision ………………………………………………………………………………… Mon
OS kernel build time ………………………………………………………… Oct root@poseidon:/usr/obj/usr/src_tmp/amd64.amd64/sys/GENERIC 8 16:37:41 UTC 2018
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… 
TrueOS version …………………………… 
uptime ………………………………………………… 11:18
user  …………………………………………………… root

 pkg info | grep easytag   
easytag-2.4.3_1                GTK Tag editor for audio files

from the terminal (zsh)

easytag
Fontconfig error: Cannot load default config file

the window opens, but effectively  brain dead. unable to open anything or navigate anywhere

**Comment by miwi-fbsd** [comment]
does fc-cache -v -f as root solve this issue?

**Comment by miwi-fbsd** [comment]
no feedback
