### ISSUE TITLE
phototonic - running, but no window

### ISSUE THREAD

**Issue by RodMyers** [trueos/trueos-ports#57]
sudo about
Password:

===================
General information
===================

boot environment now (N) … 12.0-CURRENT-201810081824 NR 2018-10-08
       after restart (R) … 12.0-CURRENT-201810081824 NR 2018-10-08
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
    number of cores ……………… 4
host ……………………………………………………… laptop.hitwe-8.org
memory ………………………………………………… 12288 MB available, 7684 MB free
OS git branch ……………………………………………………………………………………… Mon
OS git revision ………………………………………………………………………………… Mon
OS kernel build time ………………………………………………………… Oct root@poseidon:/usr/obj/usr/src_tmp/amd64.amd64/sys/GENERIC 8 16:37:41 UTC 2018
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… 
TrueOS version …………………………… 
uptime ………………………………………………… 11:18
user  …………………………………………………… root

pkg info | grep phototonic
phototonic-2.0_1               Image viewer and organizer

if started via shell
pkg info | grep phototonic
phototonic-2.0_1               Image viewer and organizer

phototonic Pictures/Trident.png

phototonic opens with picture in place, and user can scroll pics.

if i run phototonic from the terminal (zsh), phototonic spews the message below, but for all intent and purpose never appears;

phototonic                                  
libEGL warning: DRI2: failed to authenticate
Fontconfig error: Cannot load default config file
Failed to read Exif metadata
Failed to read Exif metadata
Failed to read Exif metadata
Failed to read Exif metadata

Needing a CTRL-C to abort the program

**Comment by miwi-fbsd** [comment]
same here does fc-cache -v -f as root solve the issue?

**Comment by miwi-fbsd** [comment]
no feedback
