### ISSUE TITLE
OBS-Studio -  crashes on startup

### ISSUE THREAD

**Issue by RodMyers** [trueos/trueos-ports#58]
sudo about
Password:

===================
General information
===================

boot environment now (N) … 12.0-CURRENT-201810081824 NR 2018-10-08
       after restart (R) … 12.0-CURRENT-201810081824 NR 2018-10-08
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
    number of cores ……………… 4
host ……………………………………………………… laptop.hitwe-8.org
memory ………………………………………………… 12288 MB available, 7684 MB free
OS git branch ……………………………………………………………………………………… Mon
OS git revision ………………………………………………………………………………… Mon
OS kernel build time ………………………………………………………… Oct root@poseidon:/usr/obj/usr/src_tmp/amd64.amd64/sys/GENERIC 8 16:37:41 UTC 2018
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… 
TrueOS version …………………………… 
uptime ………………………………………………… 11:18
user  …………………………………………………… root

pkg info | grep obs-studio
obs-studio-22.0.3              Open source streaming/recording software

From the terminal, it has a popup message

Failed to initialize video. Your GPU may not be supported, or your graphics drivers may need to be updated.

the terminal messages;

obs
libEGL warning: DRI2: failed to authenticate
Fontconfig error: Cannot load default config file
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/local/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/local/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Default.qss
Attempted path: /usr/local/share/obs/obs-studio/themes/Default.qss
Attempted path: share/obs/obs-studio/license/gplv2.txt
Attempted path: /usr/local/share/obs/obs-studio/license/gplv2.txt
info: CPU Name: Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
info: CPU Speed: 2491.96MHz
info: Physical Cores: 2, Logical Cores: 4
info: Physical Memory: 11813MB Total, 7923MB Free
info: Kernel Version: FreeBSD 12.0-CURRENT
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.18.4
info: Portable mode: false
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 22.0.3 (freebsd)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
        samples per sec: 44100
        speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
error: ARB_GLX_create_context not supported!
error: Failed to create context!
error: device_create (GL) failed
error: Failed to initialize video.  Your GPU may not be supported, or your graphics drivers may need to be updated.
Could not parse application stylesheet
info: Freeing OBS context data
info: == Profiler Results =============================
info: run_program_init: 14832.4ms
info:  ┣OBSApp::AppInit: 3.24ms
info:  ┃ ┗OBSApp::InitLocale: 2.108ms
info:  ┗OBSApp::OBSInit: 229.374ms
info:    ┣obs_startup: 3.894ms
info:    ┗OBSBasic::OBSInit: 50.143ms
info:      ┣OBSBasic::InitBasicConfig: 0.31ms
info:      ┣OBSBasic::ResetAudio: 0.31ms
info:      ┗OBSBasic::ResetVideo: 48.686ms
info: obs_hotkey_thread(25ms): min=0.1ms, median=0.304ms, max=13.069ms, 99th percentile=5.153ms, 100% below 25ms
info: audio_thread(Audio): min=0.03ms, median=0.064ms, max=1.009ms, 99th percentile=0.17ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: obs_hotkey_thread(25ms): min=25.38ms, median=26.759ms, max=37.95ms, 3.98482% within ±2% of 25ms (0% lower, 96.0152% higher)
info: =================================================
info: Number of memory leaks: 174

**Comment by miwi-fbsd** [comment]
Looks like glx support is missing, what gfx card are u using? could u upload /var/log/Xorg.0.log?

**Comment by miwi-fbsd** [comment]
no feedback
