### ISSUE TITLE
thttpd patch for openrc-thttpd.in 

### ISSUE THREAD

**Issue by jimbygh** [trueos/trueos-ports#62]
When building thttpd from ports (/usr/ports/www/thttpd),  the file:
files/openrc-thttpd.in  
contains startup commands for openrc-run.  The commands are incorrect and do not provide thttpd with any configuration file.

After running make install, the resulting file of:
work/openrc-thttpd
gets put into /usr/local/etc/init.d/thttpd during the install.

The following patch fixes this problem for:
files/openrc-thttpd.in  

```
--- openrc-thttpd.in    2018-10-21 21:31:25.928953000 +0000
+++ openrc-thttpd.in.patch      2018-10-22 16:37:07.398495000 +0000
@@ -4,7 +4,7 @@
 
 command=%%PREFIX%%/sbin/thttpd
 
-thttpd_flags=${thttpd_flags:-"-C %%PREFIX%%/etc/thttpd.conf"}
+command_args=${thttpd_flags:-" -C %%PREFIX%%/etc/thttpd.conf "}
 
 depend(){
        keyword -shutdown
```

Jim B.

**Comment by kmoore134** [comment]
Thanks for the patch! Did you want to submit this as a pull-request so you get credit, or shall I just patch it here for you?

**Comment by jimbygh** [comment]
you can patch.  no need for credit.

thx!

**Comment by jimbygh** [comment]
replied via github.
you can patch and close issue.

cheers,
jpb
