### ISSUE TITLE
xmahjongg won't compile -- already talked to maintainer

### ISSUE THREAD

**Issue by RodMyers** [trueos/trueos-ports#73]
fails to compile, see below.

make
===>  License GPLv2 accepted by the user
===>   xmahjongg-3.7_3 depends on file: /usr/local/sbin/pkg - found
=> xmahjongg-3.7.tar.gz doesn't seem to exist in /usr/ports/trueos-ports/distfiles/.
=> Attempting to fetch http://www.lcdf.org/xmahjongg/xmahjongg-3.7.tar.gz
xmahjongg-3.7.tar.gz                                   538 kB 1145 kBps    00s
===> Fetching all distfiles required by xmahjongg-3.7_3 for building
===>  Extracting for xmahjongg-3.7_3
=> SHA256 Checksum OK for xmahjongg-3.7.tar.gz.
===>  Patching for xmahjongg-3.7_3
===>  Applying FreeBSD patches for xmahjongg-3.7_3
1 out of 1 hunks failed--saving rejects to include/lcdf/vector.hh.rej
=> FreeBSD patch patch-lcdf failed to apply cleanly.
=> Patch(es)  patch-include_lcdf_vector.hh applied cleanly.
*** Error code 1

Stop.
make: stopped in /usr/ports/trueos-ports/games/xmahjongg

According to maintainer, ;

Are you sure the port's work directory was clean?

j@uriah 446% make
===>  License GPLv2 accepted by the user
===>   xmahjongg-3.7_3 depends on file: /usr/local/sbin/pkg - found
=> xmahjongg-3.7.tar.gz doesn't seem to exist in /junk/FreeBSD/ports/distfiles/.
=> Attempting to fetch http://www.lcdf.org/xmahjongg/xmahjongg-3.7.tar.gz
xmahjongg-3.7.tar.gz                          100% of  538 kB  221 kBps 00m02s
===> Fetching all distfiles required by xmahjongg-3.7_3 for building
===>  Extracting for xmahjongg-3.7_3
=> SHA256 Checksum OK for xmahjongg-3.7.tar.gz.
===>  Patching for xmahjongg-3.7_3
===>  Applying FreeBSD patches for xmahjongg-3.7_3
===>   xmahjongg-3.7_3 depends on file: /usr/local/libdata/pkgconfig/x11.pc - found
===>  Configuring for xmahjongg-3.7_3
configure: loading site script /junk/FreeBSD/ports/Templates/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... (cached) /usr/bin/awk
checking whether make sets $(MAKE)... yes
...

**Comment by RodMyers** [comment]
If I remove the "files" directory, it compiles with no errors

**Comment by miwi-fbsd** [comment]
Is fixed now.
